name: Test React Frontend

on:
  push:
    branches: [front-end]
    paths:
      - 'front-end/**'
  pull_request:
    branches: [front-end]
    paths:
      - 'front-end/**'

jobs:
  test:
    name: Run React (CRA) Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./front-end

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./front-end
