name: Test Back-end

on:
  push:
    branches: [develop]
    paths:
      - 'back-end/**'
  pull_request:
    branches: [develop]
    paths:
      - 'back-end/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back-end

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Cài Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cài dependencies
        run: npm install

      - name: Chạy test
        run: npm test
